apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAidXNlcm5hbWUiOiAicHJvdGFzb3ZzZSIsCiAgICAgICJ0b2tlbiI6ICJnaHBfeW9lOENyWFNiUFRuU2RNMHBKOEVzcGlRWWJHR2dCMVo4b0tSIiwKICAgICAgImVtYWlsIjogInByb3Rhc292c2VAZ21haWwuY29tIiwKICAgICAgImF1dGgiOiAiY0hKdmRHRnpiM1p6WlRwbmFIQmZlVzlsT0VOeVdGTmlVRlJ1VTJSTk1IQktPRVZ6Y0dsUldXSkhSMmRDTVZvNGIwdFMiCiAgICB9CiAgfQp9Cg==
type: kubernetes.io/dockerconfigjson
